spring:
  application:
    name: user-service
  
  # Server configuration
  server:
    port: 8081
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
      include-exception: false
  
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.192.168.39.31.nip.io/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
    show-sql: false
    open-in-view: false
  
  # Validation configuration
  validation:
    enabled: true

# gRPC server configuration
grpc:
  server:
    port: 9090
    address: 0.0.0.0
    max-inbound-message-size: 4MB
    max-inbound-metadata-size: 8KB
    keep-alive-time: 30s
    keep-alive-timeout: 5s
    keep-alive-without-calls: false
    max-connection-idle: 60s
    max-connection-age: 120s
    max-connection-age-grace: 20s
    permit-keep-alive-time: 5s
    permit-keep-alive-without-calls: false
    reflection-service-enabled: true
    health-service-enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    inpt.aseds.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    io.grpc: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/user-service.log
    max-size: 10MB
    max-history: 30

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms

# Application specific configuration
app:
  user:
    validation:
      username:
        min-length: 3
        max-length: 100
      email:
        max-length: 100
      bio:
        max-length: 500
      search:
        min-query-length: 2
        max-results: 100
    pagination:
      default-page-size: 20
      max-page-size: 100
    cache:
      enabled: true
      ttl: 300s